import { FaUser, FaEnvelope, FaRing, FaVenusMars, FaBirthdayCake, FaStar, FaGraduationCap, FaLaptopCode, FaMoneyBillWave, FaUsers, FaRulerVertical, FaPalette, FaHome, FaMapMarkerAlt, FaHourglassHalf } from 'react-icons/fa';

export const details = [
  { label: 'Full Name', value: "fullName", icon: <FaUser /> },
  { label: 'Email', value: "email", icon: <FaEnvelope /> },
  { label: 'Marital Status', value: "isMarried", icon: <FaRing /> },
  { label: 'Gender', value: "gender", icon: <FaVenusMars /> },
  { label: 'Date of Birth', value: "dob", icon: <FaBirthdayCake /> },
  { label: 'Nakshatra', value: "nakshatra", icon: <FaStar /> },
  { label: 'Rasi', value: "rasi", icon: <FaStar /> },
  { label: 'Lagna', value: "lagna", icon: <FaStar /> },
  { label: 'Qualification', value: "qualification", icon: <FaGraduationCap /> },
  { label: 'Work', value: "work", icon: <FaLaptopCode /> },
  { label: 'Salary', value: "salary", icon: <FaMoneyBillWave /> },
  { label: "Father's Name", value: "fatherName", icon: <FaUsers /> },
  { label: "Mother's Name", value: "motherName", icon: <FaUsers /> },
  { label: 'Siblings', value: "noOfBrothers", icon: <FaUsers /> },
  { label: 'Birth Order', value: "birthOrder", icon: <FaUsers /> },
  { label: 'Expectation', value: "expectation", icon: <FaUsers /> },
  { label: 'Formalities', value: "formalities", icon: <FaUsers /> },
  { label: 'House Type', value: "houseType", icon: <FaHome /> },
  { label: 'Address', value: "address", icon: <FaMapMarkerAlt /> },
  { label: 'Dasha Period', value: "dashaPeriod", icon: <FaHourglassHalf /> },
  { label: 'Height', value: "height", icon: <FaRulerVertical /> },
  { label: 'Color', value: "color", icon: <FaPalette /> },
]

export const user = {
  fullName: "raj",
  email: "raj7@gmail.com",
  images: [
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'https://images.unsplash.com/photo-1479936343636-73cdc5aae0c3?q=80&w=1780&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'https://images.unsplash.com/photo-1479936343636-73cdc5aae0c3?q=80&w=1780&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  ],
  isMarried: true,
  gender: "male",
  dob: "21-06-2002 10:10 AM",
  nakshatra: "nagam",
  rasi: "thulam",
  lagna: "mirugam",
  qualification: "bsc",
  work: "it",
  salary: 25000,
  fatherName: "nallu",
  motherName: "angali",
  noOfBrothers: 1,
  noOfSisters: 2,
  birthOrder: 2,
  expectation: "nothing else",
  formalities: "all",
  houseType: "own",
  address: "chennai",
  dashaPeriod: "4months",
  height: "180",
  color: "white",
}