import { FaUser, FaEnvelope, FaRing, FaVenusMars, FaBirthdayCake, FaStar, FaGraduationCap, FaLaptopCode, FaMoneyBillWave, FaUsers, FaRulerVertical, FaPalette, FaHome, FaMapMarkerAlt, FaHourglassHalf } from 'react-icons/fa';

export const details = [
  { label: 'Full Name', value: "fullName", icon: <FaUser /> },
  { label: 'Email', value: "email", icon: <FaEnvelope /> },
  { label: 'Marital Status', value: "isMarried", icon: <FaRing /> },
  { label: 'Gender', value: "gender", icon: <FaVenusMars /> },
  { label: 'Date of Birth', value: "dob", icon: <FaBirthdayCake /> },
  { label: 'Nakshatra', value: "nakshatra", icon: <FaStar /> },
  { label: 'Rasi', value: "rasi", icon: <FaStar /> },
  { label: 'Lagna', value: "lagna", icon: <FaStar /> },
  { label: 'Qualification', value: "qualification", icon: <FaGraduationCap /> },
  { label: 'Work', value: "work", icon: <FaLaptopCode /> },
  { label: 'Salary', value: "salary", icon: <FaMoneyBillWave /> },
  { label: "Father's Name", value: "fatherName", icon: <FaUsers /> },
  { label: "Mother's Name", value: "motherName", icon: <FaUsers /> },
  { label: 'Siblings', value: "noOfBrothers", icon: <FaUsers /> },
  { label: 'Birth Order', value: "birthOrder", icon: <FaUsers /> },
  { label: 'Expectation', value: "expectation", icon: <FaUsers /> },
  { label: 'Formalities', value: "formalities", icon: <FaUsers /> },
  { label: 'House Type', value: "houseType", icon: <FaHome /> },
  { label: 'Address', value: "address", icon: <FaMapMarkerAlt /> },
  { label: 'Dasha Period', value: "dashaPeriod", icon: <FaHourglassHalf /> },
  { label: 'Height', value: "height", icon: <FaRulerVertical /> },
  { label: 'Color', value: "color", icon: <FaPalette /> },
]